app_name = "test_app"
app_title = "test_app"
app_publisher = "Unknown"
app_description = "App generated by workflow"
app_email = "email@example.com"
app_license = "MIT"
# Further configuration options are commented out for convenience.
# Apps
# ------------------

# required_apps = []

# Each item in the list will be shown as an app in the apps page
# add_to_apps_screen = [
#     {
#         "name": "test_app",
#         "logo": "/assets/test_app/logo.png",
#         "title": "test_app",
#         "route": "/test_app",
#         "has_permission": "test_app.api.permission.has_app_permission"
#     }
# ]
